/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Datos.Conexion;
import Datos.Socio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Anahi Silvana Brao
 */
public class Estadisticas extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    private Statement sentencia;
    private ResultSet rsDatos;

    Connection connection;//para la Conexion
    PreparedStatement preparedStatement;//para preparar las querys
    ResultSet resultSet;//para recibir resultados de una cosulta
    Socio ES = new Socio();

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
        // listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscarTodo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnListarSocios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Socios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotalActivo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Estadisticas");

        buscarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodoActionPerformed(evt);
            }
        });
        buscarTodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarTodoKeyPressed(evt);
            }
        });

        jButton1.setText("Generar Grafico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Buscar");

        btnListarSocios.setText("Listar");
        btnListarSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarSociosActionPerformed(evt);
            }
        });

        tabla_Socios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        jScrollPane1.setViewportView(tabla_Socios);

        jLabel3.setText("Total Moroso = ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Total Activo =");

        txtTotalActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListarSocios)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarSocios)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void listar() {

        /* String[] titulos = {"id_socio1", "legajo_socio", "nombre", "apellido", "dni", "telefono", "domicilio",
            "estado_pago", "categoria", "estado", "cuilcuit", "email", "fechaNac"};
        System.out.println("hola si funciona!!!!lllllllllll");
        String[] registros = new String[50];
        String sql = "SELECT *FROM socio";

        model = new DefaultTableModel(null, titulos);

        try {
            Connection cn = Conexion.Cadena();
            sentencia = (Statement) cn.createStatement();
            rsDatos = sentencia.executeQuery(sql);

            while (rsDatos.next()) {
                registros[0] = rsDatos.getString("id_socio");
                System.out.println("hola si funciona!!!!");
                registros[1] = rsDatos.getString("legajo_socio");
                registros[2] = rsDatos.getString("nombre");
                registros[3] = rsDatos.getString("apellido");
                registros[4] = rsDatos.getString("dni");
                registros[5] = rsDatos.getString("telefono");
                registros[6] = rsDatos.getString("domicilio");
                registros[7] = rsDatos.getString("estado_pago");
                registros[8] = rsDatos.getString("categoria");
                registros[9] = rsDatos.getString("estado");
                registros[10] = rsDatos.getString("cuilcuit");
                registros[11] = rsDatos.getString("email");
                registros[12] = rsDatos.getString("fechaNac");
                System.out.println("sigue funcionando!!!!");
                model.addRow(registros);
            }
            tabla_Socios.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, closable, title, HEIGHT);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Estadisticas.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }
    private void buscarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTodoActionPerformed

    //Busqueda general de cualquier informacion referida a los socios  
    private void buscarTodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTodoKeyPressed

        String[] titulos = {"id_socio", "legajo_socio", "nombre", "apellido", "dni", "telefono", "domicilio",
            "estado_pago", "categoria", "estado", "cuilcuit", "email", "fechaNac"};

        String[] registros = new String[50];

        String sql = "SELECT *FROM socio WHERE id_socio LIKE '%" + buscarTodo.getText() + "%'"
                + "OR legajo_socio LIKE '%" + buscarTodo.getText() + "%'"
                + "OR nombre LIKE '%" + buscarTodo.getText() + "%'"
                + "OR apellido LIKE '%" + buscarTodo.getText() + "%'"
                + "OR dni LIKE '%" + buscarTodo.getText() + "%'"
                + "OR telefono LIKE '%" + buscarTodo.getText() + "%'"
                + "OR domicilio LIKE '%" + buscarTodo.getText() + "%'"
                + "OR estado_pago LIKE '%" + buscarTodo.getText() + "%'"
                + "OR categoria LIKE '%" + buscarTodo.getText() + "%'"
                + "OR estado LIKE '%" + buscarTodo.getText() + "%'"
                + "OR cuilcuit LIKE '%" + buscarTodo.getText() + "%'"
                + "OR email LIKE '%" + buscarTodo.getText() + "%'"
                + "OR fechaNac LIKE '%" + buscarTodo.getText() + "%'";

        model = new DefaultTableModel(null, titulos);

        try {
            connection = Conexion.Cadena();
            sentencia = (Statement) connection.createStatement();
            rsDatos = sentencia.executeQuery(sql);

            while (rsDatos.next()) {

                registros[0] = rsDatos.getString("id_socio");
                registros[1] = rsDatos.getString("legajo_socio");
                registros[2] = rsDatos.getString("nombre");
                registros[3] = rsDatos.getString("apellido");
                registros[4] = rsDatos.getString("dni");
                registros[5] = rsDatos.getString("telefono");
                registros[6] = rsDatos.getString("domicilio");
                registros[7] = rsDatos.getString("estado_pago");
                registros[8] = rsDatos.getString("categoria");
                registros[9] = rsDatos.getString("estado");
                registros[10] = rsDatos.getString("cuilcuit");
                registros[11] = rsDatos.getString("email");
                registros[12] = rsDatos.getString("fechaNac");
                model.addRow(registros);
            }
            tabla_Socios.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(Estadisticas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Estadisticas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buscarTodoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    //Obtiene una lista completa de todos los socios
    private void btnListarSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarSociosActionPerformed

        String[] titulos = {"id_socio", "legajo_socio", "nombre", "apellido", "dni", "telefono", "domicilio",
            "estado_pago", "categoria", "estado", "cuilcuit", "email", "fechaNac"};

        String[] registros = new String[50];
        String sql = "SELECT *FROM socio";

        model = new DefaultTableModel(null, titulos);

        try {
            Connection cn = Conexion.Cadena();
            sentencia = (Statement) cn.createStatement();
            rsDatos = sentencia.executeQuery(sql);

            while (rsDatos.next()) {
                registros[0] = rsDatos.getString("id_socio");
                registros[1] = rsDatos.getString("legajo_socio");
                registros[2] = rsDatos.getString("nombre");
                registros[3] = rsDatos.getString("apellido");
                registros[4] = rsDatos.getString("dni");
                registros[5] = rsDatos.getString("telefono");
                registros[6] = rsDatos.getString("domicilio");
                registros[7] = rsDatos.getString("estado_pago");
                registros[8] = rsDatos.getString("categoria");
                registros[9] = rsDatos.getString("estado");
                registros[10] = rsDatos.getString("cuilcuit");
                registros[11] = rsDatos.getString("email");
                registros[12] = rsDatos.getString("fechaNac");

                model.addRow(registros);
            }
            tabla_Socios.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, closable, title, HEIGHT);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Estadisticas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarSociosActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtTotalActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarSocios;
    private javax.swing.JTextField buscarTodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabla_Socios;
    private javax.swing.JTextField txtTotalActivo;
    // End of variables declaration//GEN-END:variables
}
