/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Datos.Conexion;
import Datos.Pagos;
import Datos.Socio;

<<<<<<< HEAD
=======

>>>>>>> master
import Datos.Resolucion;
import Datos.Socio_Crud;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Gonzalo
 */
public class Gestionar_Resoluciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form Gestionar_Resoluciones
     */
    public Gestionar_Resoluciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnBuscarSocio = new javax.swing.JButton();
        txtBuscarSocio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_listar_morosos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable_morosos = new org.jdesktop.swingx.JXTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        btnBuscarSocio.setText("Buscar");
        btnBuscarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSocioActionPerformed(evt);
            }
        });

        jLabel1.setText("Listar Socios Morosos");

        btn_listar_morosos.setText("Listar");
        btn_listar_morosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listar_morososActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar Por legajo");

        jXTable_morosos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jXTable_morosos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btn_listar_morosos))
                        .addGap(146, 146, 146)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarSocio)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_listar_morosos)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarSocio)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Suspencion", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Gestionar Resoluciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    Gestionar_Resoluciones vista = new Gestionar_Resoluciones();
    Socio modelo_socios = new Socio();
    
    //public Gestionar_Resoluciones (Gestionar_Resoluciones vista,Socio modelo_socios){
//        this.modelo_socios=modelo_socios;
//        this.vista=vista;
//        //this.vistaCRUD.btnRegistrar.addActionListener(this);
//        this.vista.btn_listar_morosos.addActionListener(this);
    //}
    public void LlenarTabla(JXTable tabla_morosos) throws ClassNotFoundException{
        DefaultTableModel modeloT = new DefaultTableModel();
        tabla_morosos.setModel(modeloT);
        
        modeloT.addColumn("Legajo");
        modeloT.addColumn("Apellido");
        modeloT.addColumn("Nombre");
        modeloT.addColumn("DNI");
        modeloT.addColumn("Estado");
        
        Object[] columna = new Object[5];
        
        int numeroRegistros= modelo_socios.listarSocios().size();
//        System.out.println(numeroRegistros);
        for ( int i=0; i<numeroRegistros;i++){
            
            verfificarPago(modelo_socios.listarSocios().get(i).getLegajo_socio());
            
            String estado=modelo_socios.listarSocios().get(i).getEstado();
            System.out.println("Estado del socio luego de verificar los pago y cambiar estado: "+estado+"\n");
            int compare = estado.compareTo("moroso");
            if(compare==0){
                columna[0]=modelo_socios.listarSocios().get(i).getLegajo_socio();
                columna[1]=modelo_socios.listarSocios().get(i).getApellido();
                columna[2]=modelo_socios.listarSocios().get(i).getNombre();
                columna[3]=modelo_socios.listarSocios().get(i).getDni();
                columna[4]=modelo_socios.listarSocios().get(i).getEstado();

                modeloT.addRow(columna);
            }
        }
        
    }//FIn-LlenarTabla
    public void verfificarPago(String leg) throws ClassNotFoundException{
        Socio nSocio = new Socio();
        Pagos ultpago = new Pagos();
        nSocio=nSocio.BuscarX(leg);
        
        ultpago=ultpago.buscarUltimoPago(nSocio.getId_socio());
        System.out.println("Socio: "+nSocio.getId_socio()+" - "+nSocio.getApellido());
        System.out.println("num Ultimo Pago: "+ultpago.getNumero_pago());
        System.out.println("Fecha Ultimo Pago: "+ultpago.getFecha());
        
            Date fechaActual = new Date();
            //System.out.println("Fecha Actual: "+fechaActual);
            Calendar fecha = Calendar.getInstance();
            int añoActual = fecha.get(Calendar.YEAR);
            int mesActual = fecha.get(Calendar.MONTH) + 1;
            int diaActual = fecha.get(Calendar.DAY_OF_MONTH);
            int horaActual = fecha.get(Calendar.HOUR_OF_DAY);
            int minutoActual = fecha.get(Calendar.MINUTE);
            int segundoActual = fecha.get(Calendar.SECOND);

            System.out.println("Fecha Actual: "+ añoActual+ "-" +mesActual +"-" +diaActual );
            //System.out.printf("Hora Actual: %02d:%02d:%02d %n", horaActual, minutoActual, segundoActual);
//            System.out.println("-------------Fecha deslosada----------------");
//            System.out.println("El año es: "+ añoActual);
//            System.out.println("El mes es: "+ mesActual);
//            System.out.println("El día es: "+ diaActual);
//            System.out.printf("La hora es: %02d %n", horaActual);
//            System.out.printf("El minuto es: %02d %n", minutoActual);
//            System.out.printf("El segundo es: %02d %n", segundoActual);
            
//          Split of a String date yyyy-MM-dd
            String ultFecha = ultpago.getFecha();
            String[] parts = ultFecha.split("-");
            String parts1_Año = parts[0]; 
            String parts2_mes = parts[1]; 
            String parts3_dia = parts[2];
            
            int ultFecha_año = Integer.parseInt(parts1_Año);
            int ultFecha_mes = Integer.parseInt(parts2_mes);
            int ultFecha_dia = Integer.parseInt(parts3_dia);
            
//            System.out.println(part1_Año+"--"+part2_mes);
            if (ultFecha_año<añoActual) {
                System.out.println("Esta Vencido, el Año actual es Mayor.\n");
            }else{
                if (mesActual>ultFecha_mes) {
                    System.out.println("Puede que ete vencido, preguntar por el dia.\n");
                    if (diaActual>ultFecha_dia) {
                        System.out.println("Esta vencido el pago. Es un Socio Moroso.\n");
                        nSocio.cambiarEstado(nSocio, 1);
                    }else{
                        System.out.println("No esta Vencido.\n");
                    }
                }else{
                    System.out.println("Esta en el mismo mes, no esta vencido.\n");
                }
                
            }
//            convert date in string
//            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
//            String fechaNac = formatoFecha.format(fechaNac_socio.getDate());
        
    }
    private void btnBuscarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSocioActionPerformed
        String estado = this.txtBuscarSocio.getText().toString();
        Conexion cn = new Conexion();
        //       Resultset rs = cn.SeleccionarUsuario(estado);
        DefaultTableModel dfmbuscar= new DefaultTableModel();
        //this.tabla.setModel(dfmbuscar);
        // dfmbuscar.setColumnIdentifiers(new Object[]{legajo_socio,nombre, apellido,dni, telefono, estado_pago,categoria,estado,cuilcuit,email});
        try {

        } catch (Exception e) {
        }

        try {
            Datos.Socio nuevoSocio = new Socio();
            nuevoSocio=nuevoSocio.BuscarX(txtBuscarSocio.getText());
            System.out.println(nuevoSocio.getNombre());
            //labelNombre.setText(nuevoSocio.getNombre());
            //labelApellido.setText(nuevoSocio.getApellido());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR!!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnBuscarSocioActionPerformed

    private void btn_listar_morososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listar_morososActionPerformed
        try {
            // TODO add your handling code here:
            LlenarTabla(jXTable_morosos);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Resoluciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_listar_morososActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarSocio;
    private javax.swing.JButton btn_listar_morosos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXTable jXTable_morosos;
    private javax.swing.JTextField txtBuscarSocio;
    // End of variables declaration//GEN-END:variables


}
