/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Datos.Conexion;
import Datos.Socio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Datos.Resolucion;
import generadorPDF.generarPDF;
import java.util.Calendar;
import java.util.Date;
import Datos.Pagos;
import Datos.Usuario;
import java.sql.SQLException;

/**
 *
 * @author Anahi
 */
public class Gestionar_Pagos extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public Gestionar_Pagos() {
        initComponents();
        this.deshabilitarCampos();
    }
    Connection connection;//para la Conexion
    PreparedStatement preparedStatement;//para preparar las querys
    ResultSet resultSet;//para recibir resultados de una cosulta
    Socio NS = new Socio();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelPago = new javax.swing.JPanel();
        labelMontoTotal = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtLegajo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_ape = new javax.swing.JLabel();
        txt_nump = new javax.swing.JLabel();
        btnGuardarRegistro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labellegajo = new javax.swing.JLabel();
        txtLegajo1 = new javax.swing.JTextField();
        btnBuscarEjercicio = new javax.swing.JButton();
        labelMontoTotal1 = new javax.swing.JLabel();
        btnGuardarE = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        txtMontoTotal1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNomE = new javax.swing.JLabel();
        txtApeE = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtUltimoPagoE = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEstadoE = new javax.swing.JLabel();
        txtEstadoS = new javax.swing.JLabel();
        txtcantC = new javax.swing.JLabel();
        txtmsj = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TxtLeg = new javax.swing.JTextField();
        btn_buscarDeuda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MontoTotalD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnom = new javax.swing.JLabel();
        txtape = new javax.swing.JLabel();
        txtlegajo = new javax.swing.JLabel();
        btnGuardarD = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();
        txtUltimoPago = new javax.swing.JLabel();
        txtMesDebe = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdS = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setClosable(true);

        labelMontoTotal.setText("Monto Total:");

        txtMontoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoTotalActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Legajo");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombre:");

        jLabel11.setText("Apellido:");

        btnGuardarRegistro.setText("Guardar Registro");
        btnGuardarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPagoLayout = new javax.swing.GroupLayout(panelPago);
        panelPago.setLayout(panelPagoLayout);
        panelPagoLayout.setHorizontalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addGap(97, 97, 97))
            .addGroup(panelPagoLayout.createSequentialGroup()
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelMontoTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPagoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPagoLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(txt_ape, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelPagoLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel11))))
                            .addComponent(jLabel10)
                            .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelPagoLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(30, 30, 30)
                                    .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(68, 68, 68)
                                    .addComponent(jButton1))
                                .addGroup(panelPagoLayout.createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addComponent(txt_nump, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        panelPagoLayout.setVerticalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagoLayout.createSequentialGroup()
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(10, 10, 10)
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ape, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(txt_nump, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMontoTotal)
                            .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)))
                .addGap(45, 45, 45)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnGuardarRegistro)
                    .addComponent(btnSalir))
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("Pago de Matricula", panelPago);

        labellegajo.setText("Legajo:");

        btnBuscarEjercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscarEjercicio.setText("Buscar");
        btnBuscarEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEjercicioActionPerformed(evt);
            }
        });

        labelMontoTotal1.setText("Monto a Pagar");

        btnGuardarE.setText("Guardar");
        btnGuardarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEActionPerformed(evt);
            }
        });

        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Apellido");

        jLabel13.setText("Nombre");

        jLabel15.setText("Fecha del Ultimo Pago");

        jLabel16.setText("Estado ");

        txtEstadoS.setText("jLabel9");

        txtcantC.setText("jLabel14");

        txtmsj.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardarE)
                .addGap(75, 75, 75)
                .addComponent(btnSalir1)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtUltimoPagoE)
                        .addGap(79, 79, 79)
                        .addComponent(txtEstadoE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(124, 124, 124)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstadoS)
                            .addComponent(jLabel16)
                            .addComponent(txtcantC))))
                .addContainerGap(319, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLegajo1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtApeE))
                                .addGap(136, 136, 136)))
                        .addGap(56, 56, 56)
                        .addComponent(btnBuscarEjercicio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelMontoTotal1)
                        .addGap(221, 221, 221)
                        .addComponent(txtmsj)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMontoTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(labellegajo)
                    .addContainerGap(528, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLegajo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEjercicio))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomE)
                    .addComponent(txtApeE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEstadoS)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUltimoPagoE)
                    .addComponent(txtEstadoE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcantC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMontoTotal1)
                    .addComponent(txtmsj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMontoTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarE)
                    .addComponent(btnSalir1))
                .addGap(52, 52, 52))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labellegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(350, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Pago de Derecho Anual de Ejercicio", jPanel2);

        jLabel3.setText("Legajo");

        TxtLeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLegActionPerformed(evt);
            }
        });

        btn_buscarDeuda.setText("Buscar");
        btn_buscarDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarDeudaActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel8.setText("Ingrese el Monto a pagar");

        btnGuardarD.setText("Guardar");
        btnGuardarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDActionPerformed(evt);
            }
        });

        btnSalir2.setText("Salir");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha del Ultimo Pago");

        jLabel7.setText("Cantidad de Meses Impagos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 110, Short.MAX_VALUE)
                                .addComponent(txtlegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(196, 196, 196))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(93, 93, 93)
                                        .addComponent(txtIdS, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarD)
                        .addGap(42, 42, 42)
                        .addComponent(btnSalir2)
                        .addGap(214, 214, 214))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btn_buscarDeuda))
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtUltimoPago)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMesDebe))
                                .addComponent(MontoTotalD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(130, 130, 130)
                                .addComponent(jLabel5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarDeuda))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdS, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtlegajo)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUltimoPago)
                    .addComponent(txtMesDebe))
                .addGap(48, 48, 48)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(MontoTotalD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarD)
                    .addComponent(btnSalir2))
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Pagar Deuda", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestionar Pagos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void deshabilitarCampos() {

        //TXT
        //   txtNumeroPago.setEnabled(false);
        txtMontoTotal.setEnabled(false);
        // fecha_pago.setEnabled(false);

        //COMBOBOX
//        Tipo.setEnabled(false);
        // Forma.setEnabled(false);
        //CantidadCuotas.setEnabled(false);
        //LABEL
        //    labelTipol.setEnabled(false);
        //labelAño.setEnabled(false);
        //labelCantCuotas.setEnabled(false);
        //labelForma.setEnabled(false);
        // labelNumeroPago.setEnabled(false);
        labelMontoTotal.setEnabled(false);

        //BOTON
        btnGuardar.setEnabled(false);
        btnGuardarE.setEnabled(false);
        txtMontoTotal1.setEnabled(false);

    }

    public void habilitarCampos() {

        //TXT
        //  txtNumeroPago.setEnabled(true);
        txtMontoTotal.setEnabled(true);
//        fecha_pago.setEnabled(true);

        //COMBOBOX
//        Tipo.setEnabled(true);
        //      Forma.setEnabled(true);
        //    CantidadCuotas.setEnabled(true);
        //LABEL
        //      labelTipol.setEnabled(true);
        //  labelAño.setEnabled(true);
        // labelCantCuotas.setEnabled(true);
        //labelForma.setEnabled(true);
        //   labelNumeroPago.setEnabled(true);
        labelMontoTotal.setEnabled(true);

        //BOTON
        btnGuardar.setEnabled(true);

    }

    // ------- Derecho de Ejercicio
    private void btnBuscarEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEjercicioActionPerformed
        String Leg = txtLegajo1.getText();

        try {
            NS = NS.BuscarX(Leg);

            System.out.println(NS.getId_socio());
            if (NS.getEstado().compareTo("activo") == 0) {
                System.out.println(NS.getApellido());
                String Id = Integer.toString(NS.getId_socio());
                String nombreS = NS.getNombre();
                String apeS = NS.getApellido();

                Date fechaActual = new Date();
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                //String fechap = formatoFecha.format(fechaActual);

                Calendar fecha = Calendar.getInstance(); //FECHA ACTUAL
                //    Calendar FechaDebe = Calendar.getInstance();
                System.out.println(fecha);

                int añoActual = fecha.get(Calendar.YEAR);
                int mesActual = fecha.get(Calendar.MONTH) + 1;
                int diaActual = fecha.get(Calendar.DAY_OF_MONTH);
                int idSocio = NS.getId_socio();

                Pagos deuda = new Pagos();
                deuda = deuda.buscarUltimoPago(idSocio);

                String FechaD = deuda.getFecha();
                System.out.println(FechaD);  // FECHA QUE DEBE EL SOCIO

                String ultFecha = deuda.getFecha();
                String[] parts = ultFecha.split("-");
                String parts1_Año = parts[0];
                String parts2_mes = parts[1];
                String parts3_dia = parts[2];

                int ultFecha_año = Integer.parseInt(parts1_Año);
                int ultFecha_mes = Integer.parseInt(parts2_mes);
                int ultFecha_dia = Integer.parseInt(parts3_dia);

                System.out.println("El mes del ultimo pago es: " + ultFecha_mes);
                System.out.println("El mes actual es: " + mesActual);

                int CantM = mesActual - ultFecha_mes - 1;

                Gestionar_Resoluciones nresolucion = new Gestionar_Resoluciones();
                nresolucion.verfificarPago2(Leg);
                Socio socioP = new Socio();
                socioP.cambiarEstado(NS, 1);

                if (NS.getEstado() != "activo") {

                    txtEstadoS.setText("El socio es Moroso");
                    txtmsj.setText("Debe pagar Sus deudas");
                    txtcantC.setText("El socio debe " + CantM + " Cuotas");
                    deshabilitarCampos();

                } else {
                    txtEstadoS.setText("El socio está al dia");

                }

                if (CantM > 0) {
                    System.out.println("El Socio debe " + CantM + " Meses");
                } else {
                    System.out.println("El socio esta al dia");
                }

                String CantMeses = String.valueOf(CantM);

                txtNomE.setText(nombreS);
                txtApeE.setText(apeS);

                txtUltimoPagoE.setText(ultFecha);
                int idSocioD = NS.getId_socio();

                String idsocio = String.valueOf(idSocioD);
                //txtIdE.setText(idsocio);

                habilitarCampos();

            } else {
                JOptionPane.showMessageDialog(null, "No es Activo");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Pagos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnBuscarEjercicioActionPerformed

    private void btnGuardarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEActionPerformed

        String Leg = txtLegajo1.getText();

        try {
            NS = NS.BuscarX(Leg);
            String Id = Integer.toString(NS.getId_socio());

            Date fechaActual = new Date();
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            String fechap = formatoFecha.format(fechaActual);

            Calendar fecha = Calendar.getInstance();
            int añoActual = fecha.get(Calendar.YEAR);
            // int mesActual = fecha.get(Calendar.MONTH);

            String TipoP = "Cuota de Ejercicio";

            System.out.println(Leg);

            connection = Conexion.Cadena();
            preparedStatement = connection.prepareStatement("INSERT INTO pago (numero_pago, monto_total, fecha, id_socio,tipo) VALUES (?,?,?,?,?)");

            //String numP= txtNumeroPago.getText();
            String numP = añoActual + "/" + Leg;
            preparedStatement.setString(1, numP);   //txtNumeroPago.getText()
            // preparedStatement.setString(2, Tipo.getSelectedItem().toString());
            // preparedStatement.setString(3, Forma.getSelectedItem().toString());
            //preparedStatement.setString(4, CantidadCuotas.getSelectedItem().toString());
            preparedStatement.setString(2, txtMontoTotal1.getText());

            //  SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            //  String fecha = formatoFecha.format(fecha_pago.getDate());
            preparedStatement.setString(3, fechap);
            // preparedStatement.setString(6, fecha.getDateFormatString());
            preparedStatement.setString(4, Id);
            preparedStatement.setString(5, TipoP);

            int res = preparedStatement.executeUpdate();
            if (res > 0) {
                System.out.println(NS.getId_socio());
                NS.setEstado("Activo");
                // 1 = Matriculacion
                // 2 = suspension
                int estadoE = 1;
                Resolucion nuevaR = new Resolucion();
                nuevaR = nuevaR.GenerarResolucion(NS, estadoE);
                //generar PDF
                generarPDF pdf = new generarPDF();
                pdf.generarPDF_Resolucion(NS, nuevaR.getNumero_resolucion(), 1);
                // Estado de Ejercicio 

                JOptionPane.showMessageDialog(null, "Pago Realizado");

                int estadoES = 2;
                Socio nuevoS = new Socio();
                nuevoS.cambiarEstado(NS, estadoES);

                //   guardarRegistro(id_U);
            } else {
                JOptionPane.showMessageDialog(null, "Error de Operación");
                //LimpiarCajas();
            }

            connection.close();

        } catch (Exception ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_btnGuardarEActionPerformed

    /*   public void guardarRegistro(int idU) throws ClassNotFoundException, SQLException {

        int idReg = 0;
        connection = Conexion.Cadena();
        preparedStatement = connection.prepareStatement("INSERT INTO registro (id_registro, id_usuario) VALUES (?,?)");

        preparedStatement.setInt(1, idReg);
        preparedStatement.setInt(2, idU);
        System.out.println("se guardo correctamente");
    }*/

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    // ---------------------PAGO DE Matricula

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String Leg = txtLegajo.getText();

        try {
            NS = NS.BuscarX(Leg);

            System.out.println(NS.getId_socio());
            if (NS.getEstado().compareTo("aspirante") == 0) {
                System.out.println(NS.getApellido());
                // String Id = Integer.toString(NS.getId_socio());
                String nomS = NS.getNombre();
                String apeS = NS.getApellido();
                //txtID_Socio.setText(Id);
                txt_nom.setText(nomS);
                txt_ape.setText(apeS);

                habilitarCampos();

            } else {
                JOptionPane.showMessageDialog(null, "No es aspirante");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Pagos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String Lega = txtLegajo.getText();
        try {
            NS = NS.BuscarX(Lega);
            String Id = Integer.toString(NS.getId_socio());

            Date fechaActual = new Date();
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            String fechap = formatoFecha.format(fechaActual);

            Calendar fecha = Calendar.getInstance();
            int año = fecha.get(Calendar.YEAR);

            String TipoP = "matricula";

            System.out.println(Lega);

            connection = Conexion.Cadena();
            preparedStatement = connection.prepareStatement("INSERT INTO pago (numero_pago, monto_total, fecha, id_socio,tipo) VALUES (?,?,?,?,?)");

            //String numP= txtNumeroPago.getText();
            String numP = año + "/" + Lega;
            preparedStatement.setString(1, numP);   //txtNumeroPago.getText()
            // preparedStatement.setString(2, Tipo.getSelectedItem().toString());
            // preparedStatement.setString(3, Forma.getSelectedItem().toString());
            //preparedStatement.setString(4, CantidadCuotas.getSelectedItem().toString());
            preparedStatement.setString(2, txtMontoTotal.getText());

            //  SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            //  String fecha = formatoFecha.format(fecha_pago.getDate());
            preparedStatement.setString(3, fechap);
            // preparedStatement.setString(6, fecha.getDateFormatString());
            preparedStatement.setString(4, Id);
            preparedStatement.setString(5, TipoP);

            int res = preparedStatement.executeUpdate();
            if (res > 0) {
                System.out.println(NS.getId_socio());
                NS.setEstado("socio");

                //Estado del Socio
                int estadoES = 2;
                Socio nuevoS = new Socio();
                nuevoS.cambiarEstado(NS, estadoES);

                // 1 = Matriculacion
                // 2 = suspension
                int estadoE = 1;

                Resolucion nuevaR = new Resolucion();
                nuevaR = nuevaR.GenerarResolucion(NS, estadoE);
                //generar PDF
                generarPDF pdf = new generarPDF();
                pdf.generarPDF_Resolucion(NS, nuevaR.getNumero_resolucion(), 1);

                JOptionPane.showMessageDialog(null, "Pago Realizado");

            } else {
                JOptionPane.showMessageDialog(null, "Error de Operación");
                //LimpiarCajas();
            }

            connection.close();

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtMontoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoTotalActionPerformed

    // ---------------------PAGO DE DEUDA
    private void btn_buscarDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarDeudaActionPerformed

        String Leg = TxtLeg.getText();

        try {
            NS = NS.BuscarX(Leg);

            System.out.println(NS.getId_socio());
            if (NS.getEstado().compareTo("moroso") == 0) {
                System.out.println(NS.getApellido());
                String Id = Integer.toString(NS.getId_socio());
                String nombreS = NS.getNombre();
                String apeS = NS.getApellido();

                Date fechaActual = new Date();
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                //String fechap = formatoFecha.format(fechaActual);

                Calendar fecha = Calendar.getInstance(); //FECHA ACTUAL
                //    Calendar FechaDebe = Calendar.getInstance();
                System.out.println(fecha);

                int añoActual = fecha.get(Calendar.YEAR);
                int mesActual = fecha.get(Calendar.MONTH) + 1;
                int idSocio = NS.getId_socio();

                Pagos deuda = new Pagos();
                deuda = deuda.buscarUltimoPago(idSocio);

                String FechaD = deuda.getFecha();
                System.out.println(FechaD);  // FECHA QUE DEBE EL SOCIO

                String ultFecha = deuda.getFecha();
                String[] parts = ultFecha.split("-");
                String parts1_Año = parts[0];
                String parts2_mes = parts[1];
                String parts3_dia = parts[2];

                int ultFecha_año = Integer.parseInt(parts1_Año);
                int ultFecha_mes = Integer.parseInt(parts2_mes);
                int ultFecha_dia = Integer.parseInt(parts3_dia);

                System.out.println("el mes que debe el socio es;" + ultFecha_mes);
                System.out.println("El mes actual es: " + mesActual);

                int CantM = mesActual - ultFecha_mes - 1;
                if (CantM > 0) {
                    System.out.println("El Socio debe " + CantM + " Meses");
                } else {
                    System.out.println("El socio esta al dia");
                }

                //   int MesD= FechaD.get(Calendar.MONTH);
//                System.out.println( "Mes que debe: "+MesD);
                String CantMeses = String.valueOf(CantM);

                txtnom.setText(nombreS);
                txtape.setText(apeS);
                txtUltimoPago.setText(ultFecha);
                int idSocioD = NS.getId_socio();
                String idsocio = String.valueOf(idSocioD);
                // txtIdS.setText(idsocio);

                if (CantM < 0) {
                    // No tendra que mostrar nunca porque si el socio no debe no deberia entrar
                    txtMesDebe.setText("1");
                    System.out.println("Socio al dia");
                } else {
                    txtMesDebe.setText(CantMeses + " Meses");
                }

                habilitarCampos();

            } else {
                JOptionPane.showMessageDialog(null, "No es Moroso");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Pagos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_buscarDeudaActionPerformed

    private void TxtLegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLegActionPerformed

    private void btnGuardarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDActionPerformed

        String Lega = TxtLeg.getText();
        try {
            NS = NS.BuscarX(Lega);
            String Id = Integer.toString(NS.getId_socio());

            Date fechaActual = new Date();
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            String fechap = formatoFecha.format(fechaActual);

            Calendar fecha = Calendar.getInstance();
            int añoActual = fecha.get(Calendar.YEAR);
            // int mesActual = fecha.get(Calendar.MONTH);

            String TipoP = "Pago de Deuda";

            System.out.println(Lega);

            connection = Conexion.Cadena();
            preparedStatement = connection.prepareStatement("INSERT INTO pago (numero_pago, monto_total, fecha, id_socio,tipo) VALUES (?,?,?,?,?)");

            //String numP= txtNumeroPago.getText();
            String numP = añoActual + "/" + Lega;
            preparedStatement.setString(1, numP);   //txtNumeroPago.getText()
            // preparedStatement.setString(2, Tipo.getSelectedItem().toString());
            // preparedStatement.setString(3, Forma.getSelectedItem().toString());
            //preparedStatement.setString(4, CantidadCuotas.getSelectedItem().toString());
            preparedStatement.setString(2, MontoTotalD.getText());

            //  SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            //  String fecha = formatoFecha.format(fecha_pago.getDate());
            preparedStatement.setString(3, fechap);
            // preparedStatement.setString(6, fecha.getDateFormatString());
            preparedStatement.setString(4, Id);
            preparedStatement.setString(5, TipoP);

            int res = preparedStatement.executeUpdate();
            if (res > 0) {
                System.out.println(NS.getId_socio());
                NS.setEstado("Activo");
                // 1 = Matriculacion
                // 2 = suspension
                int estadoE = 1;
                Resolucion nuevaR = new Resolucion();
                nuevaR = nuevaR.GenerarResolucion(NS, estadoE);
                //generar PDF
                generarPDF pdf = new generarPDF();
                pdf.generarPDF_Resolucion(NS, nuevaR.getNumero_resolucion(), 1);

                JOptionPane.showMessageDialog(null, "Pago Realizado");

                int estadoES = 2;
                Socio nuevoS = new Socio();
                nuevoS.cambiarEstado(NS, estadoES);

            } else {
                JOptionPane.showMessageDialog(null, "Error de Operación");
                //LimpiarCajas();
            }

            connection.close();

        } catch (Exception ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_btnGuardarDActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalir2ActionPerformed

    //guardar registro de pago
    private void btnGuardarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRegistroActionPerformed

        int idReg = 0;
        String nombre = "nom"; //user.getNombre();
        String contraseña = "pass"; //user.getContraseña();
        Usuario user = new Usuario();
        try {
            connection = Conexion.Cadena();
            preparedStatement = connection.prepareStatement("INSERT INTO registro (id_registro, id_usuario) VALUES (?,?)");

            user = user.buscarUsuario(nombre, contraseña);
            System.out.println("Id Usuario: " + user.getNombre());
            preparedStatement.setInt(1, idReg);
            System.out.println("Id Registro: " + idReg);
            //preparedStatement.setInt(2, user.getId());
            preparedStatement.setString(2, user.getNombre());
            
            //falta hora

            int res = preparedStatement.executeUpdate();
            if (res > 0) {
                System.out.println("Se Guardo orrectamente");
                JOptionPane.showMessageDialog(null, "Registro Guardado");

            } else {
                JOptionPane.showMessageDialog(null, "Error de Operación");

            }

            connection.close();

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    /*
    }//GEN-LAST:event_btnGuardarRegistroActionPerformed

*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MontoTotalD;
    private javax.swing.JTextField TxtLeg;
    private javax.swing.JButton btnBuscarEjercicio;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarD;
    private javax.swing.JButton btnGuardarE;
    private javax.swing.JButton btnGuardarRegistro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JButton btn_buscarDeuda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelMontoTotal;
    private javax.swing.JLabel labelMontoTotal1;
    private javax.swing.JLabel labellegajo;
    private javax.swing.JPanel panelPago;
    private javax.swing.JLabel txtApeE;
    private javax.swing.JLabel txtEstadoE;
    private javax.swing.JLabel txtEstadoS;
    private javax.swing.JLabel txtIdS;
    private javax.swing.JTextField txtLegajo;
    private javax.swing.JTextField txtLegajo1;
    private javax.swing.JLabel txtMesDebe;
    private javax.swing.JTextField txtMontoTotal;
    private javax.swing.JTextField txtMontoTotal1;
    private javax.swing.JLabel txtNomE;
    private javax.swing.JLabel txtUltimoPago;
    private javax.swing.JLabel txtUltimoPagoE;
    private javax.swing.JLabel txt_ape;
    private javax.swing.JLabel txt_nom;
    private javax.swing.JLabel txt_nump;
    private javax.swing.JLabel txtape;
    private javax.swing.JLabel txtcantC;
    private javax.swing.JLabel txtlegajo;
    private javax.swing.JLabel txtmsj;
    private javax.swing.JLabel txtnom;
    // End of variables declaration//GEN-END:variables
}
