/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Datos.Registro;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Gonzalo
 */
public class Listar_Registros extends javax.swing.JInternalFrame {

    /**
     * Creates new form registros
     */
    public Listar_Registros() {
        initComponents();
    }
    Registro modelo = new Registro();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_registros = new org.jdesktop.swingx.JXTable();
        btnListar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        Tabla_registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Legajo", "Apellido", "Nombre", "DNI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla_registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_registrosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tabla_registrosMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_registros);

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checklist.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel1.setText("Registro de Actividad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnListar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnListar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tabla_registrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_registrosMouseClicked
        
    }//GEN-LAST:event_Tabla_registrosMouseClicked

    private void Tabla_registrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_registrosMouseExited

    }//GEN-LAST:event_Tabla_registrosMouseExited

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
         try {
            // TODO add your handling code here:
            LlenarTabla(Tabla_registros);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestionar_Resoluciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarActionPerformed
    public void LlenarTabla(JXTable tabla) throws ClassNotFoundException{
        
        DefaultTableModel modeloT = new DefaultTableModel();
        tabla.setModel(modeloT);
        
        modeloT.addColumn("Usuario");
        modeloT.addColumn("Fecha");
        modeloT.addColumn("Descripcion");
        
        Object[] columna = new Object[3];
        
        int numeroRegistros= modelo.listar().size();
        for ( int i=0; i<numeroRegistros;i++){
                columna[0]=modelo.listar().get(i).getId_usuario();
                columna[1]=modelo.listar().get(i).getFecha();
                columna[2]=modelo.listar().get(i).getDescripcion();
                modeloT.addRow(columna);
        }
        
    }//FIn-LlenarTabla

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.jdesktop.swingx.JXTable Tabla_registros;
    public javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
